# Generated by Django 5.1.3 on 2024-12-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='enable_pass',
            field=models.CharField(default='', max_length=128, verbose_name='特权密码'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(max_length=128, unique=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=128, verbose_name='设备名'),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=128, verbose_name='登录密码'),
        ),
    ]
