# Generated by Django 5.1.3 on 2024-12-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_cmdb', '0002_device_enable_pass_alter_device_ip_alter_device_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=128, verbose_name='厂商')),
                ('cmd', models.CharField(blank=True, max_length=128, verbose_name='命令')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '巡检命令',
                'verbose_name_plural': '巡检命令',
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.AlterField(
            model_name='device',
            name='enable_pass',
            field=models.CharField(default='enable_password', max_length=128, verbose_name='特权密码'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=128, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='设备名'),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(default='<PASSWORD>', max_length=128, verbose_name='登录密码'),
        ),
        migrations.AlterField(
            model_name='device',
            name='platform',
            field=models.CharField(default='cisco_ios', max_length=128, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='device',
            name='series',
            field=models.CharField(blank=True, max_length=128, verbose_name='系列'),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(default='admin', max_length=128, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(blank=True, choices=[('0', 'Cisco'), ('1', 'Huawei'), ('2', 'H3C')], max_length=128, verbose_name='厂商'),
        ),
    ]
