# Generated by Django 5.1.3 on 2024-12-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_cmdb', '0003_command_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='platform',
            field=models.CharField(default='cisco_ios', max_length=128, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='command',
            name='cmd',
            field=models.TextField(blank=True, verbose_name='命令'),
        ),
    ]
