# Generated by Django 5.1.3 on 2024-12-16 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_cmdb', '0005_device_conn_timeout_device_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=128, verbose_name='执行的命令')),
                ('config_file', models.FileField(upload_to='ConfigBackup', verbose_name='配置文件')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_cmdb.device', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '配置备份',
                'verbose_name_plural': '配置备份',
            },
        ),
    ]
